### ISSUE TITLE
[q] sample input files for cellular automata

### ISSUE THREAD

**Issue by hpjeonGIT** [FLAME-HPC/xparser#17]
Dear developers,

I am not sure if this is the right place to ask but would like to ask you sample input files for Flame-HPC.
We're trying to simulate microstructure evolution, and looking for any similar input files (functions.c, model.xml, 0.xml) of similar systems like Cellular Automata. We found RAL reports of cellular  automata but included codes seem not working with FlameHPC (also init_start_state.py is not found). 
Could you share such inputs of examples ? Any comments are appreciated.

Thanks,

BJ

**Comment by zauster** [comment]
The Circles model is available in the git repo: https://github.com/FLAME-HPC/FLAME-HPC.github.io/tree/master/models/circles
You have to delete the `.txt` endings.
A sample input would be this:
[0.xml.txt](https://github.com/FLAME-HPC/xparser/files/2114467/0.xml.txt) (again delete the ending)

**Comment by hpjeonGIT** [comment]
Thanks for the reply. Just it was all to all and I was looking for neighborhood interactions only. I just found that box3d in filter does the work. Thank you again.
