### ISSUE TITLE
calculation of agents movement question 

### ISSUE THREAD

**Issue by teddy4445** [FLAME-HPC/xparser#7]
I try to simulate a movement of many robots swims in a pipe filled with water.
The question is what of the 2 following options are the correct one:
1. FLAME calculate Navier - Stocks once across the pipe and then calculate the movement of the robot using the additional power they create to find the movement in this iteration?
2. In each Iteration, FLAME calculate for each robot it's local Navier - Stocks or uses the previous movement and powers of the robot in the Navier - Stocks calculation to gain its current movement?
Thanks ahead,
Teddy

**Comment by mondus** [comment]
Hi @teddy4445. I am not clear exactly what you are trying to do. FLAME is iterative so if you are planning on numerically solving the Navier Stokes equations then you would do this using approach 2.
